on:
  pull_request:
    types: [labeled]
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Automatic Rebase
      uses: BhavinBathani/rebase-by-label@develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
